

projects_expand_school = ['school_state_AK', 'school_state_AL', 'school_state_AR', 'school_state_AZ', 'school_state_CA', 'school_state_CO', 'school_state_CT', 'school_state_DC', 'school_state_DE', 'school_state_FL', 'school_state_GA', 'school_state_HI', 'school_state_IA', 'school_state_ID', 'school_state_IL', 'school_state_IN', 'school_state_KS', 'school_state_KY', 'school_state_LA', 'school_state_La', 'school_state_MA', 'school_state_MD', 'school_state_ME', 'school_state_MI', 'school_state_MN', 'school_state_MO', 'school_state_MS', 'school_state_MT', 'school_state_NC', 'school_state_ND', 'school_state_NE', 'school_state_NH', 'school_state_NJ', 'school_state_NM', 'school_state_NV', 'school_state_NY', 'school_state_OH', 'school_state_OK', 'school_state_OR', 'school_state_PA', 'school_state_RI', 'school_state_SC', 'school_state_SD', 'school_state_TN', 'school_state_TX', 'school_state_UT', 'school_state_VA', 'school_state_VT', 'school_state_WA', 'school_state_WI', 'school_state_WV', 'school_state_WY',]

projects_expand_other = ['teacher_prefix_Dr.', 'teacher_prefix_Mr.', 'teacher_prefix_Mr. & Mrs.', 'teacher_prefix_Mrs.', 'teacher_prefix_Ms.', 'resource_type_Books', 'resource_type_Other', 'resource_type_Supplies', 'resource_type_Technology', 'resource_type_Trips', 'resource_type_Visitors', 'school_metro_enum', 'school_charter_01', 'school_magnet_01', 'school_year_round_01', 'school_nlns_01', 'school_kipp_01', 'school_charter_ready_promise_01', 'teacher_teach_for_america_01', 'teacher_ny_teaching_fellow_01', 'eligible_double_your_impact_match_01', 'eligible_almost_home_match_01', 'grade_level_enum']

projects_expand_primary = ['primary_focus_subject_Applied Sciences', 'primary_focus_subject_Character Education', 'primary_focus_subject_Civics & Government', 'primary_focus_subject_College & Career Prep', 'primary_focus_subject_Community Service', 'primary_focus_subject_ESL', 'primary_focus_subject_Early Development', 'primary_focus_subject_Economics', 'primary_focus_subject_Environmental Science', 'primary_focus_subject_Extracurricular', 'primary_focus_subject_Foreign Languages', 'primary_focus_subject_Gym & Fitness', 'primary_focus_subject_Health & Life Science', 'primary_focus_subject_Health & Wellness', 'primary_focus_subject_History & Geography', 'primary_focus_subject_Literacy', 'primary_focus_subject_Literature & Writing', 'primary_focus_subject_Mathematics', 'primary_focus_subject_Music', 'primary_focus_subject_Nutrition', 'primary_focus_subject_Other', 'primary_focus_subject_Parent Involvement', 'primary_focus_subject_Performing Arts', 'primary_focus_subject_Social Sciences', 'primary_focus_subject_Special Needs', 'primary_focus_subject_Sports', 'primary_focus_subject_Visual Arts', 'primary_focus_area_Applied Learning', 'primary_focus_area_Health & Sports', 'primary_focus_area_History & Civics', 'primary_focus_area_Literacy & Language', 'primary_focus_area_Math & Science', 'primary_focus_area_Music & The Arts', 'primary_focus_area_Special Needs', ]

projects_expand_secondary = ['secondary_focus_subject_Applied Sciences', 'secondary_focus_subject_Character Education', 'secondary_focus_subject_Civics & Government', 'secondary_focus_subject_College & Career Prep', 'secondary_focus_subject_Community Service', 'secondary_focus_subject_ESL', 'secondary_focus_subject_Early Development', 'secondary_focus_subject_Economics', 'secondary_focus_subject_Environmental Science', 'secondary_focus_subject_Extracurricular', 'secondary_focus_subject_Foreign Languages', 'secondary_focus_subject_Gym & Fitness', 'secondary_focus_subject_Health & Life Science', 'secondary_focus_subject_Health & Wellness', 'secondary_focus_subject_History & Geography', 'secondary_focus_subject_Literacy', 'secondary_focus_subject_Literature & Writing', 'secondary_focus_subject_Mathematics', 'secondary_focus_subject_Music', 'secondary_focus_subject_Nutrition', 'secondary_focus_subject_Other', 'secondary_focus_subject_Parent Involvement', 'secondary_focus_subject_Performing Arts', 'secondary_focus_subject_Social Sciences', 'secondary_focus_subject_Special Needs', 'secondary_focus_subject_Sports', 'secondary_focus_subject_Visual Arts', 'secondary_focus_area_Applied Learning', 'secondary_focus_area_Health & Sports', 'secondary_focus_area_History & Civics', 'secondary_focus_area_Literacy & Language', 'secondary_focus_area_Math & Science', 'secondary_focus_area_Music & The Arts', 'secondary_focus_area_Special Needs', ]

projects_expand = []
projects_expand.extend(projects_expand_school)
projects_expand.extend(projects_expand_other)
projects_expand.extend(projects_expand_primary)
projects_expand.extend(projects_expand_secondary)

teachers = ['proposed_project']
teachers_before = ['teacher_essay_count']
